<?php


use Phinx\Seed\AbstractSeed;

class AgentSeeder extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     */
    public function run()
    {
        $items = $this->agent();
        $data = [];
        foreach ($items as $item) {
            $data[] = [
               'registration'=> $item['mat_agnt'],
               'name'=> strtolower($item['nom_agnt']),
               'first_name'=> strtolower($item['pnom_agnt']),
               'slug'=> join('-', explode(' ', trim(''. strtolower($item['nom_agnt']).''.strtolower($item['pnom_agnt']).''))),
               'place_of_birth'=> $item['lieu_naiss'],
               'father_name'=> $item['nom_pere'],
               'mother_name'=>$item['nom_mere'],
                'child'=>$item['nbr_enfant'],
               'contact_emergency'=> $item['contact_pers_urg'],
               'phone1'=> $item['tel_agnt'],
               'e_mail'=>$item['email_agnt'],
               'service_taked_at'=>$item['pr_p_serv'],
               'birth_date'=>$item['date_naiss'],
               'created_at'=> date('Y-m-d H:i:s'),
            ];
        }
        $this->table('agents')
                ->insert($data)
                ->save();
    }
    
    private function getSlug($name1, $name2)
    {
        $explode = [];
        $next = $name1.''.$name2;
        $explode = explode(' ', $next);
        $joined = implode('-', $explode);
        return strtolower($joined) ;
    }


    private function agent()
    {
        return [
        ['id_agnt' => '18','mat_agnt' => '02014 23 W','nom_agnt' => 'ACHI ','pnom_agnt' => 'ABLAN NALBA PAULINE ','date_naiss' => '1978-05-17','lieu_naiss' => 'Bouaké','sexe' => 'Feminin ','nom_pere' => 'Achi Yapo','nom_mere' => 'Ta Lou Nakoné ','contact_pers_urg' => 'Mere Nakoné 08 72 25 53/Mme Achi EUPHRAISIE 05 07 84 80 ','tel_agnt' => '07 31 02 69/ 45 68 55 38','email_agnt' => 'paulineachi@yahoo.fr','sit_mat' => '1 ','pr_p_serv' => '2014-01-02','nbr_enfant' => '0','id_service' => '4','id_grade' => '16','id_categorie' => '22','id_fonction' => '6','id_statut' => '1','id_profession' => '8','id_diplome' => '1'],
        ['id_agnt' => '19','mat_agnt' => null,'nom_agnt' => 'ADOU','pnom_agnt' => ' GNANE SYLVIE JULIANA','date_naiss' => '1989-11-05','lieu_naiss' => 'LOCODJRO','sexe' => 'Feminin ','nom_pere' => 'ADOU GEORGES','nom_mere' => 'LASME MARRE MONIQUE','contact_pers_urg' => null,'tel_agnt' => '02 91 61 90/ 09 99 44 42','email_agnt' => 'julianaadou@yahoo.fr','sit_mat' => '1 ','pr_p_serv' => '2017-05-26','nbr_enfant' => '1','id_service' => '25','id_grade' => '3','id_categorie' => '11','id_fonction' => '6','id_statut' => '2','id_profession' => '2','id_diplome' => '24'],
        ['id_agnt' => '20','mat_agnt' => '02014 37 K','nom_agnt' => 'AKRE ','pnom_agnt' => 'AFFIBE ANTOINETTE','date_naiss' => '1969-04-06','lieu_naiss' => 'Bonoua','sexe' => 'Feminin ','nom_pere' => 'NOGBOU AKRE BERNARD','nom_mere' => 'AHOULOU EPSE NOPGBOU MARIE THERESE','contact_pers_urg' => 'Akre Mathe 06 12 64 12','tel_agnt' => '01 54 91 18','email_agnt' => 'antoinetteakre@yahoo.fr ','sit_mat' => null,'pr_p_serv' => '2014-12-02','nbr_enfant' => '0','id_service' => null,'id_grade' => '16','id_categorie' => '22','id_fonction' => '6','id_statut' => '1','id_profession' => '28','id_diplome' => '24'],
        ['id_agnt' => '21','mat_agnt' => '291 811 K','nom_agnt' => 'AMALAMAN','pnom_agnt' => ' SYLVAIN','date_naiss' => '1969-02-19','lieu_naiss' => 'Treichville-Abidjan','sexe' => 'Masculin','nom_pere' => 'Amalaman Soboré','nom_mere' => 'Kouayamé Agbona','contact_pers_urg' => null,'tel_agnt' => '07895777 / 41740001','email_agnt' => 'a_sylvain2001@yahoo.fr','sit_mat' => '2','pr_p_serv' => '2002-12-02','nbr_enfant' => '4','id_service' => '27','id_grade' => '1','id_categorie' => '11','id_fonction' => '3','id_statut' => '2','id_profession' => '3','id_diplome' => '24'],
        ['id_agnt' => '23','mat_agnt' => '02014 27 A','nom_agnt' => 'ANDOBLE','pnom_agnt' => ' YAO CHRISTIAN ','date_naiss' => '1981-09-08','lieu_naiss' => 'Bouaké','sexe' => 'Masculin','nom_pere' => 'Adoblé-Yao Kouamé Antonin','nom_mere' => 'Kouassi Ouaka Christine','contact_pers_urg' => 'Dr ANDOBLE Yao Valerie 57 55 78 63 /Andoble Yao Michael 08 97 76 14 ','tel_agnt' => '47 66 57 65 /41 41 22 22 ','email_agnt' => 'scay067@yahoo.fr','sit_mat' => '1 ','pr_p_serv' => '2014-01-02','nbr_enfant' => '1','id_service' => '3','id_grade' => '16','id_categorie' => '22','id_fonction' => '6','id_statut' => '1','id_profession' => '5','id_diplome' => '3'],
        ['id_agnt' => '24','mat_agnt' => null,'nom_agnt' => 'ANE','pnom_agnt' => ' KABLAN PAUL-EMILE','date_naiss' => '1987-12-04','lieu_naiss' => 'PORT BOUET','sexe' => 'Masculin','nom_pere' => 'ANE OI ANE','nom_mere' => 'BOSSON AMA','contact_pers_urg' => null,'tel_agnt' => '47616681/40719309','email_agnt' => 'emilekablan1987@gmail.com','sit_mat' => '1 ','pr_p_serv' => '2017-04-13','nbr_enfant' => '1','id_service' => '4','id_grade' => '3','id_categorie' => '11','id_fonction' => '6','id_statut' => '2','id_profession' => '6','id_diplome' => '24'],
        ['id_agnt' => '25','mat_agnt' => '287 567 S','nom_agnt' => 'ASSI','pnom_agnt' => ' ADOU NICOMEDE','date_naiss' => '1972-02-01','lieu_naiss' => 'Yakassé-Attobrou','sexe' => 'Masculin','nom_pere' => 'ASSI Akissi Alfred','nom_mere' => 'Boyo Assi Bah','contact_pers_urg' => 'Ebrottié Martine 03891800 05253834','tel_agnt' => '08369598/ 03184353','email_agnt' => 'assiadou4@gmail.com','sit_mat' => '1 ','pr_p_serv' => '2009-04-01','nbr_enfant' => '6','id_service' => '9','id_grade' => '2','id_categorie' => '11','id_fonction' => '3','id_statut' => '2','id_profession' => '7','id_diplome' => '24'],
        ['id_agnt' => '26','mat_agnt' => '02002 11 K','nom_agnt' => 'ATSE','pnom_agnt' => ' M\'BO ARMELLE ROSINE','date_naiss' => '1975-08-16','lieu_naiss' => null,'sexe' => 'Feminin ','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '77 06 49 66','email_agnt' => 'armelbel@yahoo,fr','sit_mat' => '2','pr_p_serv' => '2002-01-01','nbr_enfant' => null,'id_service' => '30','id_grade' => '16','id_categorie' => '22','id_fonction' => '6','id_statut' => '1','id_profession' => '28','id_diplome' => '25'],
        ['id_agnt' => '28','mat_agnt' => '01998 02 B','nom_agnt' => 'BAHONTO','pnom_agnt' => ' NEE NANOU AKA MADELEINE','date_naiss' => '1966-08-04','lieu_naiss' => 'Abidjan','sexe' => 'Feminin ','nom_pere' => 'Nanou Aka ','nom_mere' => 'Kassi Blagoh','contact_pers_urg' => null,'tel_agnt' => '07 79 00 25 ','email_agnt' => 'madbahonto@gmail.com','sit_mat' => '2','pr_p_serv' => '2003-01-02','nbr_enfant' => '4','id_service' => '5','id_grade' => '16','id_categorie' => '22','id_fonction' => '6','id_statut' => '1','id_profession' => '14','id_diplome' => '5'],
        ['id_agnt' => '34','mat_agnt' => '02014 20 T','nom_agnt' => 'ATTINGRE','pnom_agnt' => ' DAVY ARNAUD NIANGORAN','date_naiss' => '1981-07-03','lieu_naiss' => 'Treichville','sexe' => 'Masculin','nom_pere' => 'Attingré Alain Paul Emmanuel','nom_mere' => 'Nadaud Roh Monique ','contact_pers_urg' => 'Nadaud Moniqe 07 21 01 10 /20 30 55 15 ','tel_agnt' => '09 57 16 95 / 06 00 08 84','email_agnt' => 'bamboo_adou@yahoo.fr ','sit_mat' => '1 ','pr_p_serv' => '2014-01-02','nbr_enfant' => '2','id_service' => '4','id_grade' => '16','id_categorie' => '22','id_fonction' => '6','id_statut' => '1','id_profession' => '8','id_diplome' => '4'],
        ['id_agnt' => '36','mat_agnt' => '02014 41 O','nom_agnt' => 'BROUH','pnom_agnt' => ' KOUASSI SERGES PACOME','date_naiss' => '1972-02-01','lieu_naiss' => 'Diangobo (S/P Yakass2-Attobrou)','sexe' => 'Masculin','nom_pere' => 'Brou Yapo ','nom_mere' => 'Adonpo Akaba','contact_pers_urg' => 'Prof Brouh  07 77 36 49 ','tel_agnt' => '09 71 96 11 / 03 27 72 62 ','email_agnt' => 'pcbrouh@yahoo.fr','sit_mat' => 'Célibataire ','pr_p_serv' => '2014-01-02','nbr_enfant' => '2','id_service' => '10','id_grade' => '16','id_categorie' => '22','id_fonction' => '6','id_statut' => '1','id_profession' => '9','id_diplome' => '6'],
        ['id_agnt' => '37','mat_agnt' => '156 322 Y','nom_agnt' => 'CISSE','pnom_agnt' => ' MAMADOU','date_naiss' => '1955-07-23','lieu_naiss' => 'Adzopé','sexe' => 'Masculin','nom_pere' => 'Cissé Abou','nom_mere' => 'Diomandé Charlotte','contact_pers_urg' => 'Mme Cisse 07 77 63 26 ','tel_agnt' => '07 87 23 28 ','email_agnt' => 'drcissem@yahoo.fr','sit_mat' => '2','pr_p_serv' => '2000-10-09','nbr_enfant' => '1','id_service' => null,'id_grade' => '2','id_categorie' => '11','id_fonction' => '2','id_statut' => '2','id_profession' => '10','id_diplome' => '24'],
        ['id_agnt' => '38','mat_agnt' => '02014 43 Q','nom_agnt' => 'COULIBALY','pnom_agnt' => ' SANGA ZOUMANA','date_naiss' => '1982-12-06','lieu_naiss' => 'Paoufla (S/P Zuénoula)','sexe' => 'Masculin','nom_pere' => 'Koulibaly Yaya','nom_mere' => 'Salimata Koné','contact_pers_urg' => 'ouattara Karim 01 01 09 05/ 07 42 82 35','tel_agnt' => '57 02 36 91 ','email_agnt' => 'sanguesangue@yahoo.com','sit_mat' => '1 ','pr_p_serv' => '2014-01-02','nbr_enfant' => '1','id_service' => '9','id_grade' => '16','id_categorie' => '22','id_fonction' => '6','id_statut' => '1','id_profession' => '11','id_diplome' => '7'],
        ['id_agnt' => '39','mat_agnt' => '02014 28 B','nom_agnt' => 'DEGNY','pnom_agnt' => ' EGNAMBY ANNE-MARIE','date_naiss' => '1981-01-10','lieu_naiss' => 'Deux Plateaux','sexe' => 'Feminin ','nom_pere' => 'N\'Drin Degny Amessan','nom_mere' => 'Gnanago Koti Alphonsine','contact_pers_urg' => 'Degny Alfred 08 22 41 40 ','tel_agnt' => '07 00 80  90 / 44 76 55 10 ','email_agnt' => 'anne_degny@yahoo.fr','sit_mat' => '1 ','pr_p_serv' => '2014-01-02','nbr_enfant' => '1','id_service' => '25','id_grade' => '16','id_categorie' => '22','id_fonction' => '6','id_statut' => '1','id_profession' => '12','id_diplome' => '8'],
        ['id_agnt' => '40','mat_agnt' => '01998 04 D','nom_agnt' => 'DIBI','pnom_agnt' => ' NEE EDJEME N\'GUESSAN SOLANGE ','date_naiss' => '1963-12-25','lieu_naiss' => 'Bécédi (commune de Sikensi)','sexe' => 'Feminin ','nom_pere' => 'Edjémé N\'Guessan Denis','nom_mere' => 'N\'Guessan Amani Jacqueline','contact_pers_urg' => '49 46 277 30 ','tel_agnt' => '07  68 54 68 / 03 75 04 99 ','email_agnt' => 'edjeme@mail.com','sit_mat' => '2','pr_p_serv' => '2003-01-06','nbr_enfant' => '3','id_service' => '4','id_grade' => '16','id_categorie' => '22','id_fonction' => '3','id_statut' => '1','id_profession' => '14','id_diplome' => '5'],
        ['id_agnt' => '41','mat_agnt' => '02017 04 D','nom_agnt' => 'DJEBRY','pnom_agnt' => ' AHOBA EHOUMAN JEAN BAPTISTE ASSOMPTION','date_naiss' => '1988-03-26','lieu_naiss' => 'TREICHVILLE','sexe' => 'Masculin','nom_pere' => 'DJEBRY KOTCHA BERNARD','nom_mere' => 'ADELAIDE VAISSAY','contact_pers_urg' => 'DJEBRY Emmanuella 49 85 19 16','tel_agnt' => '09636953','email_agnt' => 'djebryjeanbaptiste@gmail.com','sit_mat' => '1 ','pr_p_serv' => '2017-04-07','nbr_enfant' => '0','id_service' => '1','id_grade' => '16','id_categorie' => '22','id_fonction' => '6','id_statut' => '1','id_profession' => '1','id_diplome' => '23'],
        ['id_agnt' => '42','mat_agnt' => null,'nom_agnt' => 'DOSSO','pnom_agnt' => ' LAMANTA','date_naiss' => '1990-03-10','lieu_naiss' => 'BOUAFLE','sexe' => 'Feminin ','nom_pere' => 'DOSSO KARAMOKO','nom_mere' => 'AFFOUSSATA','contact_pers_urg' => 'ZOUMANA DOSSO 09002425/42778990','tel_agnt' => '08 45 43 37','email_agnt' => 'lamtydos@yahoo.fr','sit_mat' => '1 ','pr_p_serv' => '2017-04-13','nbr_enfant' => '0','id_service' => '4','id_grade' => '4','id_categorie' => '12','id_fonction' => '6','id_statut' => '2','id_profession' => '4','id_diplome' => '24'],
        ['id_agnt' => '43','mat_agnt' => '365 512 Y','nom_agnt' => 'DOUA ','pnom_agnt' => 'NEE GBEHE MAXIMINE GISELE','date_naiss' => '1970-05-28','lieu_naiss' => 'Toulepleu','sexe' => 'Feminin ','nom_pere' => 'Gbéhé Gadé Miché','nom_mere' => 'Zéadé Thérese','contact_pers_urg' => 'Zeade theresse 07 33 20 820/ 07 67 19 73 ','tel_agnt' => '07 80 98 93 / 04 05 89 22 ','email_agnt' => 'doua_gisele@yahoo.fr','sit_mat' => '2','pr_p_serv' => '2010-12-15','nbr_enfant' => '3','id_service' => '25','id_grade' => '3','id_categorie' => '11','id_fonction' => '2','id_statut' => '2','id_profession' => '13','id_diplome' => '24'],
        ['id_agnt' => '44','mat_agnt' => '02017 46 T','nom_agnt' => 'DOUAYOUA','pnom_agnt' => ' NEE BOTI TRAZIE LOU BOZIE RACHELLE','date_naiss' => '1976-05-30','lieu_naiss' => 'Abobo (s/p Bingerville)','sexe' => 'Feminin ','nom_pere' => 'Boti Bi Trazié','nom_mere' => 'Boti Lou Bema','contact_pers_urg' => 'Mr Douayoua 78 17 30 80 ','tel_agnt' => '49 38 16 91 / 01 03 28 95 ','email_agnt' => 'rbdouayoua@gmal.com','sit_mat' => '2','pr_p_serv' => '2002-03-01','nbr_enfant' => '3','id_service' => '3','id_grade' => '16','id_categorie' => '22','id_fonction' => null,'id_statut' => '1','id_profession' => '29','id_diplome' => '9'],
        ['id_agnt' => '45','mat_agnt' => '02004 25 Y','nom_agnt' => 'EBROTTIE ','pnom_agnt' => ' N\'GANZA JEAN MARCEL ','date_naiss' => '1977-05-10','lieu_naiss' => 'Arrah ','sexe' => 'Masculin','nom_pere' => 'Ebrottié Yomanfo ','nom_mere' => 'Méa Niankon','contact_pers_urg' => 'Ehouman blandine  44 06 22 44 ','tel_agnt' => '08 75   69 23 ','email_agnt' => 'ebrotierjeanmarcel@yahoo.fr','sit_mat' => '1 ','pr_p_serv' => '2014-01-02','nbr_enfant' => '3','id_service' => '25','id_grade' => '16','id_categorie' => '22','id_fonction' => '6','id_statut' => '1','id_profession' => '30','id_diplome' => '10'],
        ['id_agnt' => '46','mat_agnt' => '283 154 Y','nom_agnt' => 'ELEGAN','pnom_agnt' => ' LAZARD KOUASSI','date_naiss' => '1973-12-17','lieu_naiss' => 'Abongoua (S/P Arrah)','sexe' => 'Masculin','nom_pere' => 'Elegan Kouassi','nom_mere' => 'Assalé N\'Gbra','contact_pers_urg' => 'Fofana Hamed  01 91 85 55  Anne Marie  06 59 78 49','tel_agnt' => '40 19 12 36  ','email_agnt' => 'lazardelegan@gmail.com','sit_mat' => '1  ','pr_p_serv' => '2014-02-10','nbr_enfant' => '3','id_service' => '27','id_grade' => '3','id_categorie' => '11','id_fonction' => '6','id_statut' => '2','id_profession' => '7','id_diplome' => '24'],
        ['id_agnt' => '47','mat_agnt' => '02000 08 H','nom_agnt' => 'ESSANI ','pnom_agnt' => 'ALOU LUCIEN ','date_naiss' => '1966-05-31','lieu_naiss' => 'Adiaké','sexe' => 'Masculin','nom_pere' => 'Nogbou Kouakou Essani','nom_mere' => 'Amouyé Attoua','contact_pers_urg' => null,'tel_agnt' => '01 33 61 33 ','email_agnt' => null,'sit_mat' => null,'pr_p_serv' => '2002-01-01','nbr_enfant' => null,'id_service' => '9','id_grade' => '16','id_categorie' => '22','id_fonction' => '6','id_statut' => '1','id_profession' => '11','id_diplome' => '11'],
        ['id_agnt' => '48','mat_agnt' => '02013 18 R','nom_agnt' => 'ETTIEN','pnom_agnt' => ' ADJOUA ALBERTINE EPSE DASSE','date_naiss' => '1982-03-15','lieu_naiss' => 'Adjamé (220 lgts)','sexe' => 'Feminin ','nom_pere' => 'Ettien Anoumou Jean-Claude','nom_mere' => 'Mian Bouadoua','contact_pers_urg' => 'Mr DASSE 05 62 16 97/07 12 65 92 / 58 31 99 78 ','tel_agnt' => '57 65 33 37  ','email_agnt' => 'adebatina@hotmail.fr','sit_mat' => '2','pr_p_serv' => '2013-07-01','nbr_enfant' => '3','id_service' => '4','id_grade' => '16','id_categorie' => '22','id_fonction' => '6','id_statut' => '1','id_profession' => '14','id_diplome' => '5'],
        ['id_agnt' => '49','mat_agnt' => '02014 35 I','nom_agnt' => 'GBA ','pnom_agnt' => 'MONNE PATRICIA','date_naiss' => '1986-02-15','lieu_naiss' => null,'sexe' => 'Feminin ','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => 'Mme GBA Estelle 09 25 97 80','tel_agnt' => '07 24 20 69 ','email_agnt' => 'gba_patricia@yahoo.fr','sit_mat' => null,'pr_p_serv' => '2014-01-02','nbr_enfant' => null,'id_service' => null,'id_grade' => '16','id_categorie' => '22','id_fonction' => '6','id_statut' => '1','id_profession' => '14','id_diplome' => '5'],
        ['id_agnt' => '50','mat_agnt' => '231 687 S','nom_agnt' => 'GBE','pnom_agnt' => ' NONDAI DIDIE ','date_naiss' => '1988-01-02','lieu_naiss' => null,'sexe' => 'Masculin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => 'Mme GBE Agathe 05 09 30 44 ','tel_agnt' => '47 08 78 19 ','email_agnt' => 'gbdidier@yahoo.fr','sit_mat' => null,'pr_p_serv' => '2014-10-03','nbr_enfant' => null,'id_service' => '31','id_grade' => '1','id_categorie' => '11','id_fonction' => '1','id_statut' => '2','id_profession' => '15','id_diplome' => '24'],
        ['id_agnt' => '51','mat_agnt' => '02014 32 F','nom_agnt' => 'GNAHOUA','pnom_agnt' => ' BANON ELODIE EPSE ADOU','date_naiss' => '1986-09-16','lieu_naiss' => 'Abobo','sexe' => 'Feminin ','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => 'Mr Adou 59 86 57 37','tel_agnt' => '47 01 71 67 ','email_agnt' => 'elogne@yahoo.fr','sit_mat' => null,'pr_p_serv' => '2014-01-02','nbr_enfant' => null,'id_service' => '28','id_grade' => '7','id_categorie' => null,'id_fonction' => '6','id_statut' => '1','id_profession' => '31','id_diplome' => '12'],
        ['id_agnt' => '52','mat_agnt' => '360 744 Y','nom_agnt' => 'GUEU','pnom_agnt' => ' BANTI PHILOMENE','date_naiss' => '1979-09-06','lieu_naiss' => 'Abobo ','sexe' => 'Feminin ','nom_pere' => 'Gueu Douen Félix','nom_mere' => 'Boh Makenleu','contact_pers_urg' => 'Gueu Félix 07 45 77 79','tel_agnt' => '08 95 33 69 ','email_agnt' => 'gphilomene@yahoo.fr','sit_mat' => '1 ','pr_p_serv' => '2014-12-15','nbr_enfant' => '1','id_service' => '7','id_grade' => '4','id_categorie' => '12','id_fonction' => '3','id_statut' => '2','id_profession' => '16','id_diplome' => '24'],
        ['id_agnt' => '53','mat_agnt' => '317 035 M','nom_agnt' => 'IREGBE ','pnom_agnt' => 'MANAN FLORENT','date_naiss' => '1974-05-06','lieu_naiss' => 'Oumé','sexe' => 'Masculin','nom_pere' => 'Iré gbé Zéba','nom_mere' => 'Tiama Yaoli Lucie','contact_pers_urg' => 'Kouamé Diaboa Omer 07 88 90 12','tel_agnt' => '47 97 27 12 ','email_agnt' => 'florent_manan@yahoo.fr','sit_mat' => '1 ','pr_p_serv' => '2006-03-09','nbr_enfant' => null,'id_service' => '28','id_grade' => '4','id_categorie' => '12','id_fonction' => '6','id_statut' => '2','id_profession' => '17','id_diplome' => '24'],
        ['id_agnt' => '54','mat_agnt' => '373 015 Z','nom_agnt' => 'KANDE','pnom_agnt' => ' MAMADOU','date_naiss' => '1986-03-28','lieu_naiss' => 'Abobo','sexe' => 'Masculin','nom_pere' => 'Amadou Kandé','nom_mere' => 'Natognin Kandé','contact_pers_urg' => null,'tel_agnt' => '48 86 50 28','email_agnt' => 'Mkande051@gmail,com','sit_mat' => '1 ','pr_p_serv' => '2014-01-02','nbr_enfant' => '0','id_service' => '27','id_grade' => '4','id_categorie' => '12','id_fonction' => '6','id_statut' => '2','id_profession' => '19','id_diplome' => '24'],
        ['id_agnt' => '55','mat_agnt' => '02014 30 D','nom_agnt' => 'KODJO ','pnom_agnt' => 'AMMA PATRICIA EPSE GOSSAN','date_naiss' => '1981-07-27','lieu_naiss' => 'Abobo ','sexe' => 'Feminin ','nom_pere' => 'Kodjo Cmille','nom_mere' => 'N\'Zo Loukou Virginie','contact_pers_urg' => 'Gonssan Fréderic 06 61 23 88','tel_agnt' => '59 68 67 44 / 05 30 10 14 ','email_agnt' => 'patkodjo@yahoo.fr','sit_mat' => null,'pr_p_serv' => '2014-01-02','nbr_enfant' => '1','id_service' => null,'id_grade' => '7','id_categorie' => null,'id_fonction' => '6','id_statut' => '1','id_profession' => '27','id_diplome' => '13'],
        ['id_agnt' => '56','mat_agnt' => '02002 12 L','nom_agnt' => 'KOFFI','pnom_agnt' => ' KOUADIO MARIE PRUDENCE AHOU','date_naiss' => '1975-03-06','lieu_naiss' => 'Bouaflé','sexe' => 'Feminin ','nom_pere' => 'Koffi Kouadio Jean ','nom_mere' => 'Ahoué N\'guessan Madeleine ','contact_pers_urg' => 'Mr Wadja 77 00 94 53    Mlle koffi marie galane 07 88 97 39','tel_agnt' => '58 29 81 93 / 05 57 77 26 ','email_agnt' => 'amariprud@yahoo.fr','sit_mat' => null,'pr_p_serv' => '2002-01-01','nbr_enfant' => '1','id_service' => '27','id_grade' => '6','id_categorie' => null,'id_fonction' => '6','id_statut' => '1','id_profession' => '28','id_diplome' => '25'],
        ['id_agnt' => '57','mat_agnt' => '423 128 J','nom_agnt' => 'KOFFI ','pnom_agnt' => 'KOUAME MATHURIN','date_naiss' => '1983-11-13','lieu_naiss' => 'N\'Gorankro (S/P Sinfra)','sexe' => 'Masculin','nom_pere' => 'N\'Gatta Koffi','nom_mere' => 'Dje Affoué','contact_pers_urg' => 'Koffi Edmond 09 76 01 78','tel_agnt' => '08 87 09 37 ','email_agnt' => 'mathurskoffi@yahoo.fr','sit_mat' => '1 ','pr_p_serv' => '2016-02-12','nbr_enfant' => '0','id_service' => '3','id_grade' => '2','id_categorie' => '11','id_fonction' => '6','id_statut' => '2','id_profession' => '18','id_diplome' => '24'],
        ['id_agnt' => '58','mat_agnt' => '356 223 D','nom_agnt' => 'KOFFI ','pnom_agnt' => 'KOUASSI GUY ROGER','date_naiss' => '1977-03-14','lieu_naiss' => 'Cocody','sexe' => 'Masculin','nom_pere' => 'Koffi Bilé Bernard','nom_mere' => 'N\'Da Bilé Ya Eugeunie','contact_pers_urg' => 'Tano Affoue Patricia 49 18 75 45','tel_agnt' => '07 69 77 40 / 04 29 79 70 ','email_agnt' => 'kkroger@yahoo.fr','sit_mat' => '1 ','pr_p_serv' => '2010-07-01','nbr_enfant' => '3','id_service' => '28','id_grade' => '2','id_categorie' => '11','id_fonction' => '6','id_statut' => '2','id_profession' => '3','id_diplome' => '24'],
        ['id_agnt' => '59','mat_agnt' => '02014 22 V','nom_agnt' => 'KOHOU','pnom_agnt' => ' BLESSON JOELLE EPSE KOUAKOU MINAN','date_naiss' => '1984-09-03','lieu_naiss' => 'Dedjan S/P Bloléquin','sexe' => 'Feminin ','nom_pere' => 'Kohou René','nom_mere' => 'Djiblo Béatrice ','contact_pers_urg' => 'Mr Kouakou Minan 07 06 15 64','tel_agnt' => '58 87 20 06 ','email_agnt' => 'joelleblesson@yahoo.fr','sit_mat' => '2','pr_p_serv' => '2014-01-02','nbr_enfant' => '1','id_service' => '27','id_grade' => '6','id_categorie' => null,'id_fonction' => '6','id_statut' => '1','id_profession' => '32','id_diplome' => '16'],
        ['id_agnt' => '60','mat_agnt' => null,'nom_agnt' => 'KONAN ','pnom_agnt' => 'N\'GUESSAN ','date_naiss' => '1984-01-02','lieu_naiss' => 'ATTEKRO (S/P DIDIEVI)','sexe' => 'Masculin','nom_pere' => 'KONAN KONAN','nom_mere' => 'KONAN AKISSI','contact_pers_urg' => null,'tel_agnt' => '09 07 37 05/ 04 06 00 93','email_agnt' => 'Nkonan972@gmail.com','sit_mat' => '1 ','pr_p_serv' => '2017-04-13','nbr_enfant' => '0','id_service' => '31','id_grade' => '3','id_categorie' => '11','id_fonction' => '5','id_statut' => '2','id_profession' => '2','id_diplome' => '24'],
        ['id_agnt' => '61','mat_agnt' => '02007 15 O','nom_agnt' => 'KONATE','pnom_agnt' => ' AISTAN EPSE SIEWE','date_naiss' => '1978-09-22','lieu_naiss' => 'Abidjan-Koumassi','sexe' => 'Feminin ','nom_pere' => 'Adama Konaté','nom_mere' => 'Diarra Fanda','contact_pers_urg' => 'Mr Adama Konaté 09 21 29 58 ','tel_agnt' => '05 83 99 88 ','email_agnt' => 'aistan_2006@yahoo.fr','sit_mat' => '2','pr_p_serv' => '2007-01-01','nbr_enfant' => '0','id_service' => '28','id_grade' => null,'id_categorie' => null,'id_fonction' => '3','id_statut' => '1','id_profession' => '12','id_diplome' => '15'],
        ['id_agnt' => '62','mat_agnt' => null,'nom_agnt' => 'KONKOUGNE ','pnom_agnt' => 'ADJOUA SUZANNE','date_naiss' => '1976-08-31','lieu_naiss' => 'ADJAME','sexe' => 'Feminin ','nom_pere' => 'PND','nom_mere' => 'KONKOUGNE AFFOUE','contact_pers_urg' => null,'tel_agnt' => '07 81 94 95/ 40 06 18 42','email_agnt' => 'adjouakani34@yahoo.fr','sit_mat' => '1 ','pr_p_serv' => '2017-05-02','nbr_enfant' => '1','id_service' => '6','id_grade' => '3','id_categorie' => '11','id_fonction' => '6','id_statut' => '2','id_profession' => '2','id_diplome' => '24'],
        ['id_agnt' => '63','mat_agnt' => '02014 24 X','nom_agnt' => 'KOUAKOU','pnom_agnt' => ' KOUAKOU BLAISE','date_naiss' => '1977-09-07','lieu_naiss' => 'Assokro 2 (S/P Ouellé)','sexe' => 'Masculin','nom_pere' => 'Yao Kouakou','nom_mere' => 'Yao N\'Goran','contact_pers_urg' => 'Mr Ya Brou 07 70 94 60 / N\'goran N\'guessan 08 47 27 06 ','tel_agnt' => '08 25 55 17 ','email_agnt' => 'blaisekouakou@gmail.com','sit_mat' => 'Célibataire ','pr_p_serv' => '2014-01-01','nbr_enfant' => null,'id_service' => '27','id_grade' => '6','id_categorie' => null,'id_fonction' => '6','id_statut' => '1','id_profession' => '32','id_diplome' => '16'],
        ['id_agnt' => '64','mat_agnt' => '434866 R','nom_agnt' => 'KOUAKOU ','pnom_agnt' => 'KOUAKOU ERIC','date_naiss' => '1985-12-16','lieu_naiss' => 'DASSIOKO (S/P FRESCO)','sexe' => 'Masculin','nom_pere' => 'KOFFI KOUAKOU EDOUARD ','nom_mere' => 'N\'GOUAN ADJOUA YVONNE','contact_pers_urg' => 'KOFFI KOUAKOU EDOUARD 07590506','tel_agnt' => '07900134/01278160','email_agnt' => 'ericintello@ymail.com','sit_mat' => 'Célibataire ','pr_p_serv' => '2017-04-26','nbr_enfant' => '1','id_service' => '9','id_grade' => '4','id_categorie' => '12','id_fonction' => '6','id_statut' => '2','id_profession' => '27','id_diplome' => '24'],
        ['id_agnt' => '65','mat_agnt' => '270 100 V','nom_agnt' => 'KOUAKOU ','pnom_agnt' => 'née AYE AFFOUE AUGUSTINE','date_naiss' => '1970-12-24','lieu_naiss' => 'Banguié (S/P Rubino) ','sexe' => 'Feminin ','nom_pere' => 'Ayé Germain','nom_mere' => 'N\'Gbésso Epi','contact_pers_urg' => 'Kouakou Yao Brou  02 57 18 63 ','tel_agnt' => '08  15 38 84 ','email_agnt' => 'aye_augu@yahoo.fr','sit_mat' => '2','pr_p_serv' => '2004-01-08','nbr_enfant' => '3','id_service' => '27','id_grade' => '4','id_categorie' => '12','id_fonction' => '6','id_statut' => '2','id_profession' => '19','id_diplome' => '24'],
        ['id_agnt' => '66','mat_agnt' => '02014 26 Z','nom_agnt' => 'KOUAME','pnom_agnt' => ' KOUAKOU BONAVENTURE','date_naiss' => '1982-06-10','lieu_naiss' => 'Marcory ','sexe' => 'Masculin','nom_pere' => 'Kouamé Kouamé Kouassi','nom_mere' => 'Konan Ahou Mélanie','contact_pers_urg' => 'Mme Koffi 09 27 54 32 ','tel_agnt' => '07 28 93 49 ','email_agnt' => 'kkbonaventure@yahoo.fr','sit_mat' => null,'pr_p_serv' => '2014-01-02','nbr_enfant' => null,'id_service' => '25','id_grade' => '6','id_categorie' => null,'id_fonction' => '6','id_statut' => '1','id_profession' => '33','id_diplome' => '17'],
        ['id_agnt' => '67','mat_agnt' => '02015 44 R','nom_agnt' => 'KOUAME ','pnom_agnt' => 'PROSPER','date_naiss' => '1977-12-16','lieu_naiss' => 'Issia','sexe' => 'Masculin','nom_pere' => 'Yao Kouamé Pascal','nom_mere' => 'N\'Gbra Akissi','contact_pers_urg' => 'Mme Kouamé 06 13 84 70   /   Kouamé Jean-parfait 05 52 39 35','tel_agnt' => '57 51 52 23 ','email_agnt' => 'kouamenaser@yahoo.fr','sit_mat' => '2','pr_p_serv' => '2015-01-02','nbr_enfant' => null,'id_service' => '6','id_grade' => null,'id_categorie' => null,'id_fonction' => '3','id_statut' => '1','id_profession' => '30','id_diplome' => '10'],
        ['id_agnt' => '68','mat_agnt' => '269 689 S','nom_agnt' => 'KOUASSI','pnom_agnt' => ' BROU N\'GBIN','date_naiss' => '1968-12-01','lieu_naiss' => 'Kanango (S/P Tiébissou)','sexe' => 'Masculin','nom_pere' => 'Alloko Kouassi','nom_mere' => 'Koffi Aya','contact_pers_urg' => 'Mme N\'gbin 06 15 24 76 ','tel_agnt' => '05 64 63 93 / 01 25 55 68 ','email_agnt' => 'kouassi_ngbin@yahoo.fr','sit_mat' => '2','pr_p_serv' => '2004-01-08','nbr_enfant' => '2','id_service' => '27','id_grade' => '3','id_categorie' => '11','id_fonction' => '2','id_statut' => '2','id_profession' => '20','id_diplome' => '24'],
        ['id_agnt' => '69','mat_agnt' => '02009 09 I','nom_agnt' => 'KOUASSI ','pnom_agnt' => 'N\'KRUMAH','date_naiss' => '1967-08-29','lieu_naiss' => 'Treichville','sexe' => 'Masculin','nom_pere' => 'Kouassi Appoutou','nom_mere' => 'N\'Cho Abby ','contact_pers_urg' => 'Mme Kouassi 44 02 14 01','tel_agnt' => '06 31045 67 / 02 07 29 79  ','email_agnt' => 'jeanbatkouassi@yahoo.fr','sit_mat' => '2','pr_p_serv' => '2000-01-01','nbr_enfant' => null,'id_service' => '9','id_grade' => '10','id_categorie' => null,'id_fonction' => '6','id_statut' => '1','id_profession' => '11','id_diplome' => '11'],
        ['id_agnt' => '70','mat_agnt' => '421 047 J','nom_agnt' => 'KOUMAN','pnom_agnt' => ' OUATTARA FATIMATA','date_naiss' => '1983-03-27','lieu_naiss' => 'Abengourou','sexe' => 'Feminin ','nom_pere' => 'Kouamé Kouman dit Badaoudou','nom_mere' => 'Adja Anani','contact_pers_urg' => 'Mme Aissa 47 15 05 50','tel_agnt' => null,'email_agnt' => 'matarafaty@yahoo.fr','sit_mat' => '1 ','pr_p_serv' => '2015-12-28','nbr_enfant' => '2','id_service' => '32','id_grade' => '5','id_categorie' => '12','id_fonction' => '6','id_statut' => '2','id_profession' => '21','id_diplome' => '24'],
        ['id_agnt' => '71','mat_agnt' => '270 044 K','nom_agnt' => 'M\'BRA ','pnom_agnt' => 'KOFFI KOUA DOMINIQUE','date_naiss' => '1973-12-23','lieu_naiss' => 'M\'Batto','sexe' => 'Masculin','nom_pere' => 'M\'Bra Koffi Maurice','nom_mere' => 'Binbé Tanoh Marie-claire','contact_pers_urg' => 'Kpangni Valerie 07 28 00 47','tel_agnt' => '08 83 45 80 ','email_agnt' => 'mbradominik@gmail.com','sit_mat' => '1 ','pr_p_serv' => '2013-04-02','nbr_enfant' => '3','id_service' => '30','id_grade' => '3','id_categorie' => '11','id_fonction' => '3','id_statut' => '2','id_profession' => '22','id_diplome' => '24'],
        ['id_agnt' => '72','mat_agnt' => '437481 B','nom_agnt' => 'ME','pnom_agnt' => ' BRICE AXEL KYRILL','date_naiss' => '1989-10-20','lieu_naiss' => 'COCOCDY','sexe' => 'Masculin','nom_pere' => 'ME YAO BERNARD','nom_mere' => 'AKABO MAKOU MARIE PAULE GISELE','contact_pers_urg' => null,'tel_agnt' => '77225799/58062686','email_agnt' => 'm.brice225@gmail.com','sit_mat' => '2','pr_p_serv' => '2017-04-13','nbr_enfant' => '2','id_service' => null,'id_grade' => '4','id_categorie' => '12','id_fonction' => '6','id_statut' => '2','id_profession' => '4','id_diplome' => '24'],
        ['id_agnt' => '73','mat_agnt' => '02014 29 C','nom_agnt' => 'N\'DAMAN ','pnom_agnt' => 'AHIZA JOSETTE','date_naiss' => '1987-11-10','lieu_naiss' => 'Grand-bassam','sexe' => 'Feminin ','nom_pere' => 'N\'Daman Aka Firmin','nom_mere' => 'Kouaho Enokouba Delphine','contact_pers_urg' => 'Natchia Ahui Paul-juste 07 54 36 59','tel_agnt' => '09 09 55 79 / 45 59 90 16','email_agnt' => 'josetteahizaza@yahoo.fr','sit_mat' => '1 ','pr_p_serv' => '2014-01-02','nbr_enfant' => '0','id_service' => null,'id_grade' => '12','id_categorie' => null,'id_fonction' => '6','id_statut' => '1','id_profession' => '33','id_diplome' => '18'],
        ['id_agnt' => '74','mat_agnt' => '291 110 Y','nom_agnt' => 'OTCHONI','pnom_agnt' => ' GERMAINE GNAHORE','date_naiss' => '1968-03-20','lieu_naiss' => 'Divo','sexe' => 'Feminin ','nom_pere' => 'Otchoni Jean','nom_mere' => 'Ahoussou Amenan ','contact_pers_urg' => 'Otchoni Sabine  04 91 73 02 / 17 56 84 70 / 49 61  64 61 /05 63 25 98 ','tel_agnt' => '05 87 62 17 / 48 81 28 11 ','email_agnt' => 'germyotchoni@yahoo.com','sit_mat' => '1 ','pr_p_serv' => '2003-01-02','nbr_enfant' => '1','id_service' => null,'id_grade' => '4','id_categorie' => '12','id_fonction' => '6','id_statut' => '2','id_profession' => '26','id_diplome' => '24'],
        ['id_agnt' => '75','mat_agnt' => '387 914 G','nom_agnt' => 'OUATTARA ','pnom_agnt' => 'HAFSA','date_naiss' => '1985-01-16','lieu_naiss' => 'Treichville','sexe' => 'Feminin ','nom_pere' => 'Ouattara Ladji ','nom_mere' => 'Soro Ahoua ','contact_pers_urg' => 'Mme Ouattara Ahoua  07 44 97 25 / 02 39 24 83 ','tel_agnt' => '07 29 82 55 ','email_agnt' => 'h.ouattara@environnement.gouv.ci      ','sit_mat' => '1 ','pr_p_serv' => '2015-06-08','nbr_enfant' => '0','id_service' => '1','id_grade' => '4','id_categorie' => '12','id_fonction' => '3','id_statut' => '2','id_profession' => '1','id_diplome' => '24'],
        ['id_agnt' => '76','mat_agnt' => '047 82 0080','nom_agnt' => 'OZIGRE','pnom_agnt' => ' KOUDOU','date_naiss' => '1980-12-09','lieu_naiss' => null,'sexe' => 'Masculin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => null,'email_agnt' => null,'sit_mat' => null,'pr_p_serv' => '2012-01-10','nbr_enfant' => null,'id_service' => '33','id_grade' => '16','id_categorie' => '22','id_fonction' => null,'id_statut' => '2','id_profession' => null,'id_diplome' => '24'],
        ['id_agnt' => '77','mat_agnt' => '421 052 P','nom_agnt' => 'PAKORA','pnom_agnt' => ' YAGUI LISA CAROLE ','date_naiss' => '1980-12-09','lieu_naiss' => 'Treichville','sexe' => 'Feminin ','nom_pere' => 'Pakora Ibo Joseph','nom_mere' => 'Ablé Niana','contact_pers_urg' => null,'tel_agnt' => null,'email_agnt' => 'lcypakora@yahoo.fr','sit_mat' => '2 ','pr_p_serv' => '2015-12-28','nbr_enfant' => '1','id_service' => '32','id_grade' => '5','id_categorie' => '12','id_fonction' => '6','id_statut' => '2','id_profession' => '21','id_diplome' => '24'],
        ['id_agnt' => '78','mat_agnt' => '02014 33 G','nom_agnt' => 'SANOKO ','pnom_agnt' => 'ANZOUMANA ','date_naiss' => '1985-02-28','lieu_naiss' => 'Bouaké','sexe' => 'Masculin','nom_pere' => 'Bema Sanoko','nom_mere' => 'Konaté Saumata','contact_pers_urg' => 'Badra Ali sanogo  77 02 29 76 ','tel_agnt' => '08 99 45 55 / 03 83 95 59 ','email_agnt' => 'bazou85@yahoo.fr','sit_mat' => '1 ','pr_p_serv' => '2014-01-02','nbr_enfant' => '0','id_service' => '27','id_grade' => '13','id_categorie' => null,'id_fonction' => '6','id_statut' => '1','id_profession' => '34','id_diplome' => '19'],
        ['id_agnt' => '79','mat_agnt' => '02014 38 L','nom_agnt' => 'SILUIE','pnom_agnt' => ' DONONTON ALASSANE','date_naiss' => '1991-01-13','lieu_naiss' => 'Sinématiali','sexe' => 'Masculin','nom_pere' => 'Nangalougo Silué','nom_mere' => 'Soro Banafana','contact_pers_urg' => 'Silue Lehevro  07 20 54 30 ','tel_agnt' => ' 08 21 46 45 ','email_agnt' => 'silue2000@yahoo.f','sit_mat' => '1 ','pr_p_serv' => '2014-01-02','nbr_enfant' => '0','id_service' => '28','id_grade' => '13','id_categorie' => null,'id_fonction' => '6','id_statut' => '1','id_profession' => '35','id_diplome' => '20'],
        ['id_agnt' => '80','mat_agnt' => '02014 31 E','nom_agnt' => 'SOHOUA ','pnom_agnt' => 'AKISSI MARIE ANTOINETTE EPSE BOHUI','date_naiss' => '1981-12-15','lieu_naiss' => 'Agboville ','sexe' => 'Feminin ','nom_pere' => 'Sohoua Boni','nom_mere' => 'N\'GbakéAkissi','contact_pers_urg' => null,'tel_agnt' => '46 64 51 04','email_agnt' => 'antoinettebohui@yahoo.fr','sit_mat' => '2','pr_p_serv' => '2014-01-02','nbr_enfant' => '2','id_service' => '27','id_grade' => '7','id_categorie' => null,'id_fonction' => '6','id_statut' => '1','id_profession' => '31','id_diplome' => '12'],
        ['id_agnt' => '81','mat_agnt' => null,'nom_agnt' => 'SORHO ','pnom_agnt' => 'MEHAN LOUIS GERARD','date_naiss' => '1980-08-26','lieu_naiss' => 'BOUAKE','sexe' => 'Masculin','nom_pere' => 'SORHO N\'GOLO CHRISTIAN','nom_mere' => 'COULIBALY PEGNONNA AGNES','contact_pers_urg' => 'Mme SORHO 41 89 41 92','tel_agnt' => '41313597/','email_agnt' => 'lgsorho@gmail.com','sit_mat' => '2','pr_p_serv' => '2017-04-13','nbr_enfant' => '1','id_service' => '5','id_grade' => '4','id_categorie' => '12','id_fonction' => '6','id_statut' => '2','id_profession' => '4','id_diplome' => '24'],
        ['id_agnt' => '82','mat_agnt' => '02015 45 S','nom_agnt' => 'SORO ','pnom_agnt' => 'FOUNGOTRIGUE','date_naiss' => '1982-06-01','lieu_naiss' => 'Korhogo ','sexe' => 'Masculin','nom_pere' => 'SORO YAYA','nom_mere' => 'COULIBALY MAMA ','contact_pers_urg' => 'SIRIKI Coulibaly  07 94 07 04 ','tel_agnt' => '59 48 40 59 ','email_agnt' => 'foungsoro@yahoo.fr','sit_mat' => '1 ','pr_p_serv' => '2015-01-02','nbr_enfant' => '1','id_service' => '10','id_grade' => '14','id_categorie' => null,'id_fonction' => '3','id_statut' => '1','id_profession' => '31','id_diplome' => '21'],
        ['id_agnt' => '83','mat_agnt' => 'en cours','nom_agnt' => 'SY','pnom_agnt' => ' NEE TOURE FATOUMATA','date_naiss' => '1988-05-08','lieu_naiss' => 'ADJAME','sexe' => 'Feminin ','nom_pere' => 'TOURE IBRAHIMA','nom_mere' => 'TOURE  MAKAGBE','contact_pers_urg' => 'SY HAMADOU SAMBA 09 25 06 34','tel_agnt' => '57 80 71 46','email_agnt' => 'fatou.toure.sy@gmail','sit_mat' => '2','pr_p_serv' => '2017-04-26','nbr_enfant' => '3','id_service' => '33','id_grade' => '4','id_categorie' => '12','id_fonction' => '6','id_statut' => '2','id_profession' => '4','id_diplome' => '24'],
        ['id_agnt' => '84','mat_agnt' => '206 525 X','nom_agnt' => 'TIBE','pnom_agnt' => ' BI GOBA GUALBERT','date_naiss' => '1959-07-12','lieu_naiss' => 'Gobazra (Bonon)','sexe' => 'Masculin','nom_pere' => 'Lopoua Bi Tibé Alphonse','nom_mere' => 'Tibé Lou Zah','contact_pers_urg' => 'Tibe raymond 06 07 19 93 /Tibe Arsene 48 68 36 26','tel_agnt' => '09 92 85 09 ','email_agnt' => 'tibebigoba@gmail.com','sit_mat' => '2','pr_p_serv' => '2016-05-11','nbr_enfant' => '4','id_service' => '2','id_grade' => '3','id_categorie' => '11','id_fonction' => '3','id_statut' => '2','id_profession' => '23','id_diplome' => '24'],
        ['id_agnt' => '85','mat_agnt' => '02014 42 P','nom_agnt' => 'TOTOKRA ','pnom_agnt' => 'KOFFI RICHARD ','date_naiss' => '1973-03-03','lieu_naiss' => 'Bouaké','sexe' => 'Masculin','nom_pere' => 'Totokra Boni Sosthène','nom_mere' => 'Yao Ahou Rosalie','contact_pers_urg' => '05 71 91 32 / 01 16 20 29 ','tel_agnt' => '41 41 21 21 / 46 47 90 87 ','email_agnt' => null,'sit_mat' => '1 ','pr_p_serv' => '2014-01-02','nbr_enfant' => '1','id_service' => '9','id_grade' => '15','id_categorie' => null,'id_fonction' => '6','id_statut' => '1','id_profession' => '11','id_diplome' => '11'],
        ['id_agnt' => '86','mat_agnt' => '02014 21 U','nom_agnt' => 'WAHI ','pnom_agnt' => 'NEE ALLA JOELLE','date_naiss' => '1977-07-05','lieu_naiss' => 'Bottro ','sexe' => 'Feminin ','nom_pere' => 'Alla Yao','nom_mere' => 'COULIBALY Nicole','contact_pers_urg' => 'Mr Wahi  07 82 92 79 ','tel_agnt' => '07 49 74 65 ','email_agnt' => 'joellealla@yahoo.fr','sit_mat' => '2','pr_p_serv' => '2014-01-02','nbr_enfant' => '2','id_service' => '27','id_grade' => '6','id_categorie' => null,'id_fonction' => '6','id_statut' => '1','id_profession' => '12','id_diplome' => '15'],
        ['id_agnt' => '87','mat_agnt' => '02007 16 P','nom_agnt' => 'YAO ','pnom_agnt' => 'N\'DRI DENIS','date_naiss' => '1974-05-25','lieu_naiss' => 'Ouffoué Diékro (Yamoussoukro)','sexe' => 'Masculin','nom_pere' => 'Koffi Yao','nom_mere' => 'Koffi Aya','contact_pers_urg' => 'Mme Yao  22 00 40 13 ','tel_agnt' => '07 45 17 17 ','email_agnt' => 'yaondenis@gmail.com','sit_mat' => '2','pr_p_serv' => '2007-01-01','nbr_enfant' => '2','id_service' => '27','id_grade' => null,'id_categorie' => null,'id_fonction' => '6','id_statut' => '1','id_profession' => '34','id_diplome' => '19'],
        ['id_agnt' => '88','mat_agnt' => '02013 19 S','nom_agnt' => 'YAPI','pnom_agnt' => ' SEKA SYLVAIN','date_naiss' => '1964-03-23','lieu_naiss' => 'FIASSE (S/P YAKASSE-ATTOBROU)','sexe' => 'Masculin','nom_pere' => 'KOKOA YAPI','nom_mere' => 'KOKOA APO','contact_pers_urg' => 'Yapi Atse Augustin 57 65 31 77 ','tel_agnt' => '06 10 98 00/  47 22 11 21 ','email_agnt' => null,'sit_mat' => '1 ','pr_p_serv' => '2013-07-01','nbr_enfant' => '4','id_service' => '9','id_grade' => '10','id_categorie' => null,'id_fonction' => '6','id_statut' => '1','id_profession' => '11','id_diplome' => '11'],
        ['id_agnt' => '89','mat_agnt' => '275 892 U','nom_agnt' => 'YEO','pnom_agnt' => ' DANIEL NANGBELE','date_naiss' => '1978-06-29','lieu_naiss' => null,'sexe' => 'Masculin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => 'Mme yeo 07 67 97 71','tel_agnt' => '07 50 78 82 ','email_agnt' => 'yedana@yahoo.fr','sit_mat' => 'marié','pr_p_serv' => '2014-01-02','nbr_enfant' => null,'id_service' => null,'id_grade' => '1','id_categorie' => '11','id_fonction' => '2','id_statut' => '2','id_profession' => '24','id_diplome' => '24'],
        ['id_agnt' => '90','mat_agnt' => '02014 36 J','nom_agnt' => 'ZAGBA','pnom_agnt' => ' JEANNETTE EDITH RUTH','date_naiss' => '1978-06-29','lieu_naiss' => 'COCODY','sexe' => 'Masculin','nom_pere' => 'Zagba N\'Drin ','nom_mere' => 'Beugré Wahon Delphine','contact_pers_urg' => 'Mme Beugre Delphine ','tel_agnt' => '02 75 54 64 ','email_agnt' => 'ruthzagba@yahoo.fr','sit_mat' => '1 ','pr_p_serv' => '2014-01-02','nbr_enfant' => '0','id_service' => '3','id_grade' => '9','id_categorie' => null,'id_fonction' => '6','id_statut' => '1','id_profession' => '36','id_diplome' => '22'],
        ['id_agnt' => '92','mat_agnt' => '434858z','nom_agnt' => 'DAMOH','pnom_agnt' => 'ahounou raoul','date_naiss' => '1986-07-07','lieu_naiss' => 'grand bassam','sexe' => 'masculin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '08857385','email_agnt' => 'raouldamoh@gmail.com','sit_mat' => null,'pr_p_serv' => '2017-08-04','nbr_enfant' => null,'id_service' => '9','id_grade' => '4','id_categorie' => '12','id_fonction' => '6','id_statut' => '2','id_profession' => '19','id_diplome' => '24'],
        ['id_agnt' => '93','mat_agnt' => '388105H','nom_agnt' => 'SIE-LY','pnom_agnt' => 'anna marianne','date_naiss' => '1979-01-25','lieu_naiss' => 'ABIDJAN','sexe' => 'féminin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '08843664','email_agnt' => 'annasiely@gmail.com','sit_mat' => null,'pr_p_serv' => '2017-10-04','nbr_enfant' => null,'id_service' => '1','id_grade' => '2','id_categorie' => '11','id_fonction' => '6','id_statut' => '2','id_profession' => '28','id_diplome' => '25'],
        ['id_agnt' => '99','mat_agnt' => '453244C','nom_agnt' => 'ACHI','pnom_agnt' => 'nimba guy arnaud','date_naiss' => '1986-11-18','lieu_naiss' => 'yopougon','sexe' => 'masculin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '09286372','email_agnt' => 'achiarnaud@gmail.com','sit_mat' => null,'pr_p_serv' => '2017-10-20','nbr_enfant' => null,'id_service' => '8','id_grade' => '4','id_categorie' => '12','id_fonction' => '6','id_statut' => '2','id_profession' => '4','id_diplome' => '24'],
        ['id_agnt' => '100','mat_agnt' => '0201705L','nom_agnt' => 'LEBO','pnom_agnt' => 'lebo armel wilfried','date_naiss' => '1985-05-10','lieu_naiss' => 'Abobo','sexe' => 'masculin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '53013619','email_agnt' => 'merlow07@yahoo.fr','sit_mat' => null,'pr_p_serv' => '2017-08-18','nbr_enfant' => null,'id_service' => '7','id_grade' => '16','id_categorie' => '22','id_fonction' => '6','id_statut' => '1','id_profession' => '8','id_diplome' => '24'],
        ['id_agnt' => '101','mat_agnt' => '454824K','nom_agnt' => 'ALLIMAN','pnom_agnt' => 'adjabi christian','date_naiss' => '1986-11-12','lieu_naiss' => 'YOPOUGON','sexe' => 'masculin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '58087399','email_agnt' => 'christianadjabi@gmail.com','sit_mat' => null,'pr_p_serv' => '2018-03-07','nbr_enfant' => null,'id_service' => '25','id_grade' => '11','id_categorie' => '23','id_fonction' => '6','id_statut' => '2','id_profession' => '39','id_diplome' => '24'],
        ['id_agnt' => '102','mat_agnt' => '383170G','nom_agnt' => 'AZI','pnom_agnt' => 'georges rosard','date_naiss' => '1985-08-15','lieu_naiss' => 'BOUAFLE','sexe' => 'masculin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '08868430','email_agnt' => 'georgesazi@yahoo.fr','sit_mat' => null,'pr_p_serv' => '2017-08-08','nbr_enfant' => null,'id_service' => '10','id_grade' => '12','id_categorie' => '23','id_fonction' => '6','id_statut' => '2','id_profession' => '37','id_diplome' => '24'],
        ['id_agnt' => '103','mat_agnt' => '297323X','nom_agnt' => 'BAMBA','pnom_agnt' => 'mamery','date_naiss' => '1977-03-10','lieu_naiss' => 'TOUBA','sexe' => 'masculin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '07286195','email_agnt' => 'b.mamery@yahoo.fr','sit_mat' => null,'pr_p_serv' => '2017-07-05','nbr_enfant' => null,'id_service' => '28','id_grade' => '3','id_categorie' => '11','id_fonction' => '5','id_statut' => '2','id_profession' => '22','id_diplome' => '24'],
        ['id_agnt' => '104','mat_agnt' => '443209Q','nom_agnt' => 'BOUA','pnom_agnt' => 'djahi melissa stephanie epse dogbo','date_naiss' => '1987-06-26','lieu_naiss' => 'DIVO','sexe' => 'féminin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '07009824','email_agnt' => 'mely1987@yahoo.fr','sit_mat' => null,'pr_p_serv' => '2017-07-25','nbr_enfant' => null,'id_service' => '9','id_grade' => '10','id_categorie' => '22','id_fonction' => '6','id_statut' => '2','id_profession' => '37','id_diplome' => '24'],
        ['id_agnt' => '105','mat_agnt' => '320680L','nom_agnt' => 'DIBI','pnom_agnt' => 'didier fulgence','date_naiss' => '1980-06-23','lieu_naiss' => 'YOPOUGON','sexe' => 'masculin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '57755076','email_agnt' => 'didierfulgenced@gmail.com','sit_mat' => null,'pr_p_serv' => '2017-07-25','nbr_enfant' => null,'id_service' => '28','id_grade' => '4','id_categorie' => '12','id_fonction' => '6','id_statut' => '2','id_profession' => '17','id_diplome' => '24'],
        ['id_agnt' => '106','mat_agnt' => '454834M','nom_agnt' => 'FOFANA','pnom_agnt' => 'kopele guy abraham david','date_naiss' => '1989-09-29','lieu_naiss' => 'DIDIEVI','sexe' => 'masculin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '59746416','email_agnt' => 'fofanakopele@yahoo.fr','sit_mat' => null,'pr_p_serv' => '2018-02-08','nbr_enfant' => null,'id_service' => '28','id_grade' => '3','id_categorie' => '11','id_fonction' => '6','id_statut' => '2','id_profession' => '13','id_diplome' => '24'],
        ['id_agnt' => '107','mat_agnt' => '365678W','nom_agnt' => 'GNEGNENE','pnom_agnt' => 'armel simplice','date_naiss' => '1973-08-16','lieu_naiss' => 'FERKESSEDOUGOU','sexe' => 'masculin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '47122750','email_agnt' => 'sgnegnene@gmail.com','sit_mat' => null,'pr_p_serv' => '2017-11-12','nbr_enfant' => null,'id_service' => '8','id_grade' => '3','id_categorie' => '11','id_fonction' => '6','id_statut' => '2','id_profession' => '6','id_diplome' => '24'],
        ['id_agnt' => '108','mat_agnt' => '305387G','nom_agnt' => 'KABRAN','pnom_agnt' => 'rene','date_naiss' => '1975-03-18','lieu_naiss' => 'AGNIBILEKRO','sexe' => 'masculin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '47553740','email_agnt' => 'renekabran@yahoo.fr','sit_mat' => null,'pr_p_serv' => '2017-07-27','nbr_enfant' => null,'id_service' => '27','id_grade' => '2','id_categorie' => '11','id_fonction' => '5','id_statut' => '2','id_profession' => '18','id_diplome' => '24'],
        ['id_agnt' => '110','mat_agnt' => '395585R','nom_agnt' => 'YAO','pnom_agnt' => 'kobena noel','date_naiss' => '1971-12-23','lieu_naiss' => 'ADJAME','sexe' => 'masculin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '08202769','email_agnt' => 'yaonoelkob@gmail.com','sit_mat' => null,'pr_p_serv' => '2017-07-11','nbr_enfant' => null,'id_service' => '27','id_grade' => '4','id_categorie' => '12','id_fonction' => '5','id_statut' => '2','id_profession' => '36','id_diplome' => '24'],
        ['id_agnt' => '111','mat_agnt' => '361865E','nom_agnt' => 'KOFFI','pnom_agnt' => 'née gueu ouasseka franchise','date_naiss' => '1985-12-05','lieu_naiss' => 'Gnin Gleu','sexe' => 'féminin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '47767776','email_agnt' => 'ehisegueu@yahoo.fr','sit_mat' => null,'pr_p_serv' => '2017-06-23','nbr_enfant' => null,'id_service' => '32','id_grade' => '9','id_categorie' => '12','id_fonction' => '6','id_statut' => '2','id_profession' => '21','id_diplome' => '24'],
        ['id_agnt' => '112','mat_agnt' => '284883M','nom_agnt' => 'KOFFI','pnom_agnt' => 'kouame jean-baptiste','date_naiss' => '1964-01-01','lieu_naiss' => 'M\'bahia-Yaokro','sexe' => 'masculin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '05752551','email_agnt' => 'koffijeanbeken@gmail.com','sit_mat' => null,'pr_p_serv' => '2017-08-29','nbr_enfant' => null,'id_service' => '10','id_grade' => '15','id_categorie' => '24','id_fonction' => '6','id_statut' => '2','id_profession' => '11','id_diplome' => '24'],
        ['id_agnt' => '113','mat_agnt' => '454841U','nom_agnt' => 'KESSE','pnom_agnt' => 'manzan','date_naiss' => '1985-04-19','lieu_naiss' => 'ARRAH','sexe' => 'féminin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '57988732','email_agnt' => 'loiskesse@yahoo.fr','sit_mat' => null,'pr_p_serv' => '2018-02-08','nbr_enfant' => null,'id_service' => '30','id_grade' => '4','id_categorie' => '12','id_fonction' => '6','id_statut' => '2','id_profession' => '38','id_diplome' => '24'],
        ['id_agnt' => '114','mat_agnt' => '356712F','nom_agnt' => 'YAO','pnom_agnt' => 'koffi  eugene','date_naiss' => '2018-06-06','lieu_naiss' => 'BAMORO BOUAKE','sexe' => 'masculin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '47107273','email_agnt' => 'ykoff79@gmail.com','sit_mat' => null,'pr_p_serv' => '2018-02-02','nbr_enfant' => null,'id_service' => '27','id_grade' => '2','id_categorie' => '11','id_fonction' => '6','id_statut' => '2','id_profession' => '7','id_diplome' => '24'],
        ['id_agnt' => '115','mat_agnt' => '456695U','nom_agnt' => 'KOUASS','pnom_agnt' => 'kouadio herve','date_naiss' => '1979-12-30','lieu_naiss' => 'TAPEGUHE DALOA','sexe' => 'masculin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '07045702','email_agnt' => 'k2herve@gmail.com','sit_mat' => null,'pr_p_serv' => '2018-01-31','nbr_enfant' => null,'id_service' => '1','id_grade' => '4','id_categorie' => '12','id_fonction' => '6','id_statut' => '2','id_profession' => '28','id_diplome' => '24'],
        ['id_agnt' => '116','mat_agnt' => '298044C','nom_agnt' => 'YAPI','pnom_agnt' => 'teby bertin','date_naiss' => '1954-03-03','lieu_naiss' => 'ANYAMA','sexe' => 'masculin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '07395198','email_agnt' => 'yapiteby@gmail.com','sit_mat' => null,'pr_p_serv' => '2017-08-28','nbr_enfant' => null,'id_service' => '4','id_grade' => '15','id_categorie' => '24','id_fonction' => '6','id_statut' => '2','id_profession' => '11','id_diplome' => '24'],
        ['id_agnt' => '117','mat_agnt' => '454854Z','nom_agnt' => 'SORO','pnom_agnt' => 'tanfoltien','date_naiss' => '1989-09-29','lieu_naiss' => 'FERKESSEDOUGOU','sexe' => 'masculin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '05819970','email_agnt' => 'sorotenfoltien@yahoo.fr','sit_mat' => null,'pr_p_serv' => '2018-02-02','nbr_enfant' => null,'id_service' => '28','id_grade' => '2','id_categorie' => '11','id_fonction' => '6','id_statut' => '2','id_profession' => '3','id_diplome' => '24'],
        ['id_agnt' => '118','mat_agnt' => '366207Q','nom_agnt' => 'YOUHO','pnom_agnt' => 'zinongbo jerome','date_naiss' => '1981-01-05','lieu_naiss' => 'TAPEGHUE BUYO','sexe' => 'masculin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '08451406','email_agnt' => 'youho3@yahoo.fr','sit_mat' => null,'pr_p_serv' => '2017-09-03','nbr_enfant' => null,'id_service' => '27','id_grade' => '3','id_categorie' => '11','id_fonction' => '6','id_statut' => '2','id_profession' => '2','id_diplome' => '24'],
        ['id_agnt' => '119','mat_agnt' => '385129V','nom_agnt' => 'ZAHIRI','pnom_agnt' => 'annick','date_naiss' => '1976-08-04','lieu_naiss' => 'SAIOUA','sexe' => 'féminin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '47759556','email_agnt' => 'annickzahiri3@gmail.com','sit_mat' => null,'pr_p_serv' => '2017-06-20','nbr_enfant' => null,'id_service' => '4','id_grade' => '9','id_categorie' => '12','id_fonction' => '6','id_statut' => '2','id_profession' => '21','id_diplome' => '24'],
        ['id_agnt' => '120','mat_agnt' => '322609P','nom_agnt' => 'TANOH','pnom_agnt' => 'luc','date_naiss' => '1978-06-06','lieu_naiss' => 'TIASSALE','sexe' => 'masculin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '07407632','email_agnt' => 'artistelucas@yahoo.fr','sit_mat' => null,'pr_p_serv' => '2017-07-06','nbr_enfant' => null,'id_service' => '9','id_grade' => '1','id_categorie' => '11','id_fonction' => '6','id_statut' => '2','id_profession' => '28','id_diplome' => '24'],
        ['id_agnt' => '121','mat_agnt' => '000000','nom_agnt' => 'OZIGRE','pnom_agnt' => 'koudou','date_naiss' => '1964-12-21','lieu_naiss' => 'GAGNOA','sexe' => 'masculin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '01046876','email_agnt' => 'koudouozigre@gmail.com','sit_mat' => null,'pr_p_serv' => '2012-01-10','nbr_enfant' => null,'id_service' => '31','id_grade' => '16','id_categorie' => '22','id_fonction' => '6','id_statut' => '2','id_profession' => '28','id_diplome' => '24'],
        ['id_agnt' => '122','mat_agnt' => '343416S','nom_agnt' => 'MEA','pnom_agnt' => 'née konan ahou solange','date_naiss' => '1968-05-09','lieu_naiss' => 'TREICHVILLE','sexe' => 'féminin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '07234651','email_agnt' => 'measolo32@yahoo.fr','sit_mat' => null,'pr_p_serv' => '2017-07-25','nbr_enfant' => null,'id_service' => '28','id_grade' => '4','id_categorie' => '12','id_fonction' => '5','id_statut' => '2','id_profession' => '17','id_diplome' => '24'],
        ['id_agnt' => '123','mat_agnt' => '440456G','nom_agnt' => 'KOUAME','pnom_agnt' => 'n\'guessan paul','date_naiss' => '1976-05-31','lieu_naiss' => 'OUME','sexe' => 'masculin','nom_pere' => null,'nom_mere' => null,'contact_pers_urg' => null,'tel_agnt' => '57577238','email_agnt' => 'nsanpol@gmail.com','sit_mat' => null,'pr_p_serv' => '2017-07-21','nbr_enfant' => null,'id_service' => '29','id_grade' => '4','id_categorie' => '12','id_fonction' => '6','id_statut' => '2','id_profession' => '19','id_diplome' => '24']
        ];
    }
}
